[2024-05-29T15:49:03.006+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-29T15:49:03.048+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-05-29T15:48:52.681081+00:00 [queued]>
[2024-05-29T15:49:03.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate manual__2024-05-29T15:48:52.681081+00:00 [queued]>
[2024-05-29T15:49:03.065+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-29T15:49:03.087+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): inaccurate> on 2024-05-29 15:48:52.681081+00:00
[2024-05-29T15:49:03.097+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=867) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-29T15:49:03.099+0000] {standard_task_runner.py:63} INFO - Started process 869 to run task
[2024-05-29T15:49:03.099+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'manual__2024-05-29T15:48:52.681081+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/mydag.py', '--cfg-path', '/tmp/tmp5lekkacq']
[2024-05-29T15:49:03.104+0000] {standard_task_runner.py:91} INFO - Job 15: Subtask inaccurate
[2024-05-29T15:49:03.174+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag.inaccurate manual__2024-05-29T15:48:52.681081+00:00 [running]> on host abdc8a9dc09e
[2024-05-29T15:49:03.304+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-05-29T15:48:52.681081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-29T15:48:52.681081+00:00'
[2024-05-29T15:49:03.308+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-29T15:49:03.309+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-29T15:49:03.311+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-05-29T15:49:03.325+0000] {subprocess.py:86} INFO - Output:
[2024-05-29T15:49:03.328+0000] {subprocess.py:93} INFO - inaccurate
[2024-05-29T15:49:03.328+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-29T15:49:03.330+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-29T15:49:03.362+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=manual__2024-05-29T15:48:52.681081+00:00, execution_date=20240529T154852, start_date=20240529T154903, end_date=20240529T154903
[2024-05-29T15:49:03.395+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-29T15:49:03.425+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-29T15:49:03.429+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
